version: 2.0

references:
  triggerable-by-tag: &triggerable-by-tag
    # For a tag push unaffected by any filters, CircleCI skips the job
    # https://circleci.com/docs/2.0/workflows/#git-tag-job-execution
    filters:
      tags:
        only: /.*/
  build-lint-unit: &build-lint-unit
    requires:
      - test
      - lint
      - build

  nodelts: &nodelts
    docker:
      - image: cimg/node:lts
  browsers: &browsers
    docker:
      - image: circleci/node:12.18.3-browsers
  nodenext: &nodenext
    docker:
      - image: cimg/node:current
  node12: &node12
    docker:
      - image: cimg/node:12.18
  node10: &node10
    docker:
      - image: cimg/node:10.22
  node6: &node6
    docker:
      - image: circleci/node:6.17.1

  workspace: &workspace
    attach_workspace:
      at: ~/project
  persist: &persist
    persist_to_workspace:
      root: .
      paths:
        - .

  rebuild_test: &rebuild_test
    steps:
      - *workspace
      - run: npm rebuild
      - run: FETCH_MOCK_SRC=../cjs/server.js make test


jobs:
  checkout_code:
    <<: *nodelts
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-{{ checksum "package-lock.json" }}
      - run: if [ ! -d "node_modules" ]; then npm install --no-package-lock; fi
      - save_cache:
          key: npm-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - *persist

  build:
    <<: *nodelts
    steps:
      - *workspace
      - run: make build
      - *persist
  lint:
    <<: *nodelts
    steps:
      - *workspace
      - run: make lint-ci

  typecheck:
    <<: *nodelts
    steps:
      - *workspace
      - run: make typecheck

  test:
    <<: *nodelts
    steps:
      - *workspace
      - run: make coverage


  nodefetch2:
    <<: *nodelts
    steps:
      - *workspace
      - run: FETCH_MOCK_SRC=../cjs/server.js make test

  nodefetch1:
    <<: *nodelts
    steps:
      - *workspace
      - run: npm install node-fetch@1
      - run: FETCH_MOCK_SRC=../cjs/server.js make test

  nodefetch3:
    <<: *nodelts
    steps:
      - *workspace
      - run: npm install node-fetch@next
      - run: FETCH_MOCK_SRC=../cjs/server.js make test

  es5:
    <<: *node6
    steps:
      - *workspace
      - run: npm rebuild
      - run: FETCH_MOCK_SRC=../es5/server.js make test-es5

  # esm:
  #   <<: *nodelts
  #   steps:
  #     - *workspace
  #     - run: npm rebuild
  #     - run: make test-esm

  node12:
    <<: *node12
    <<: *rebuild_test
  node10:
    <<: *node10
    <<: *rebuild_test
  nodenext:
    <<: *nodenext
    <<: *rebuild_test

  chrome:
    <<: *browsers
    steps:
      - *workspace
      - run: TEST_BROWSER=Chrome make test-browser

  firefox:
    <<: *browsers
    steps:
      - *workspace
      - run: npm install karma-firefox-launcher
      - run: TEST_BROWSER=Firefox make test-browser

  deploy:
    <<: *nodelts
    steps:
      - *workspace
      - run: make publish


workflows:
  version: 2
  fetch-mock-ci-cd:
    jobs:
      - checkout_code: *triggerable-by-tag
      - test:
          <<: *triggerable-by-tag
          requires:
            - checkout_code
      - lint:
          <<: *triggerable-by-tag
          requires:
            - checkout_code
      - build:
          <<: *triggerable-by-tag
          requires:
            - checkout_code
      # could be parallel with build, lint, and unit but it's a slow job
      # And circlecifree tier only has 3 concurrent jobs, so overall faster
      # to defer
      - typecheck:
          <<: *triggerable-by-tag
          <<: *build-lint-unit
      - nodefetch1:
          <<: *triggerable-by-tag
          <<: *build-lint-unit
      - nodefetch2:
          <<: *triggerable-by-tag
          <<: *build-lint-unit
      - nodefetch3:
          <<: *triggerable-by-tag
          <<: *build-lint-unit
      - es5:
          <<: *triggerable-by-tag
          <<: *build-lint-unit
      # - esm:
      #     <<: *triggerable-by-tag
      #     <<: *build-lint-unit
      - node10:
          <<: *triggerable-by-tag
          <<: *build-lint-unit
      - node12:
          <<: *triggerable-by-tag
          <<: *build-lint-unit
      - nodenext:
          <<: *triggerable-by-tag
          <<: *build-lint-unit
      - chrome:
          <<: *triggerable-by-tag
          <<: *build-lint-unit
      - firefox:
          <<: *triggerable-by-tag
          <<: *build-lint-unit
      - deploy:
          context: wheresrhys-npm-publish
          requires:
            - nodefetch1
            - nodefetch2
            - nodefetch3
            - es5
            - chrome
            - firefox
            - build
            - typecheck
            - node10
            - nodenext
            - node12
            # - esm
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?\d+\.\d+\.\d+(?:-(beta|alpha)\.\d+)?$/
